#! /bin/bash

#Formatting
NORMAL="\033[0m"
BOLD="\033[1m"
DIM="\033[2m"
UNDERLINED="\033[4m"
INVERT="\033[7m"
HIDDEN="\033[8m"

#Text Color
TEXT_DEFAULT="\033[39m"
TEXT_BLACK="\033[30m"
TEXT_RED="\033[31m"
TEXT_GREEN="\033[32m"
TEXT_YELLOW="\033[33m"
TEXT_BLUE="\033[34m"
TEXT_MAGENTA="\033[35m"
TEXT_CYAN="\033[36m"
TEXT_LIGHT_GREY="\033[37m"
TEXT_DARK_GRE="\033[90m"
TEXT_LIGHT_RED="\033[91m"
TEXT_LIGHT_GREEN="\033[92m"
TEXT_LIGHT_YELLOW="\033[93m"
TEXT_LIGHT_BLUE="\033[94m"
TEXT_LIGHT_MAGENTA="\033[95m"
TEXT_LIGHT_CYAN="\033[96m"
TEXT_WHITE="\033[97m"

#Background Color
BACK_DEFAULT="\033[49m"
BACK_BLACK="\033[40m"
BACK_RED="\033[41m"
BACK_GREEN="\033[42m"
BACK_YELLOW="\033[43m"
BACK_BLUE="\033[44m"
BACK_MAGENTA="\033[45m"
BACK_CYAN="\033[46m"
BACK_LIGHT_GREY="\033[47m"
BACK_DARK_GREY="\033[100m"
BACK_LIGHT_RED="\033[101m"
BACK_LIGHT_GREEN="\033[102m"
BACK_LIGHT_YELLOW="\033[103m"
BACK_LIGHT_BLUE="\033[104m"
BACK_LIGHT_MAGENTA="\033[105m"
BACK_LIGHT_CYAN="\033[106m"
BACK_WHITE="\033[107m"

echo -e "Formatting:"
echo -e  ${NORMAL} "NORMAL" $NORMAL
echo -e  $BOLD "BOLD" $NORMAL
echo -e  $DIM "DIM" $NORMAL
echo -e  $UNDERLINED "UNDERLINED" $NORMAL
echo -e  $INVERT "INVERT" $NORMAL
echo -e  $HIDDEN "HIDDEN" $NORMAL

echo -e ""
echo -e "Text Color:"
echo -e  $TEXT_DEFAULT "TEXT_DEFAULT" $BOLD "BOLD" NORMAL
echo -e  $TEXT_BLACK "TEXT_BLACK" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_RED "TEXT_RED" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_GREEN "TEXT_GREEN" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_YELLOW "TEXT_YELLOW" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_BLUE "TEXT_BLUE" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_MAGENTA "TEXT_MAGENTA" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_CYAN "TEXT_CYAN" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_LIGHT_GREY "TEXT_LIGHT_GREY" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_LIGHT_RED "TEXT_LIGHT_RED" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_LIGHT_GREEN "TEXT_LIGHT_GREEN" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_LIGHT_YELLOW "TEXT_LIGHT_YELLOW" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_LIGHT_BLUE "TEXT_LIGHT_BLUE" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_LIGHT_MAGENTA "TEXT_LIGHT_MAGENTA" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_LIGHT_CYAN "TEXT_LIGHT_CYAN" $BOLD "BOLD" $NORMAL
echo -e  $TEXT_WHITE "TEXT_WHITE" $BOLD "BOLD" $NORMAL

echo -e ""
echo -e "Background Color:"
echo -e  $BACK_DEFAULT "BACK_DEFAULT" $BACK_DEFAULT
echo -e  $BACK_BLACK "BACK_BLACK" $BACK_DEFAULT
echo -e  $BACK_RED "BACK_RED" $BACK_DEFAULT
echo -e  $BACK_GREEN "BACK_GREEN" $BACK_DEFAULT
echo -e  $BACK_YELLOW "BACK_YELLOW" $BACK_DEFAULT
echo -e  $BACK_BLUE "BACK_BLUE" $BACK_DEFAULT
echo -e  $BACK_MAGENTA "BACK_MAGENTA" $BACK_DEFAULT
echo -e  $BACK_CYAN "BACK_CYAN" $BACK_DEFAULT
echo -e  $BACK_LIGHT_GREY "BACK_LIGHT_GREY" $BACK_DEFAULT
echo -e  $BACK_LIGHT_RED "BACK_LIGHT_RED" $BACK_DEFAULT
echo -e  $BACK_LIGHT_GREEN "BACK_LIGHT_GREEN" $BACK_DEFAULT
echo -e  $BACK_LIGHT_YELLOW "BACK_LIGHT_YELLOW" $BACK_DEFAULT
echo -e  $BACK_LIGHT_BLUE "BACK_LIGHT_BLUE" $BACK_DEFAULT
echo -e  $BACK_LIGHT_MAGENTA "BACK_LIGHT_MAGENTA" $BACK_DEFAULT
echo -e  $BACK_LIGHT_CYAN "BACK_LIGHT_CYAN" $BACK_DEFAULT
echo -e  $BACK_WHITE "BACK_WHITE" $BACK_DEFAULT

echo -e ""
echo -e "You can mix and match formatting text coloring and background coloring!"

